Repository organization/alspotron, pull requests merged in 2023-07, with the labels that each got.

#23 fix: macOS fullscreen mode
  src/Application.ts
Labels: Type: Bug, Platform: macOS, Platform: Linux (KDE), Platform: Linux (Gnome), Platform: Windows

#25 change(deps): migration from `ts-treemap-next` to `@js-sdsl/ordered-map`
  package-lock.json
  package.json
  renderer/lyrics/SideBar.tsx
  renderer/main/components/Lyrics.tsx
  renderer/main/components/PlayingInfoProvider.tsx
Labels: Type: Enhancement, Type: Dependency

#28 fix(eslint): `object-curly-spacing`을 `error`, `always`로 설정
  .eslintrc.js
  renderer/main/components/AnchoredView.tsx
  renderer/settings/containers/PositionContainer.tsx
  src/Application.ts
Labels: Type: Code Style Change

#27 feat: 자동 업데이트 알림, 업데이트 패널 구현
  index.ts
  package-lock.json
  package.json
  renderer/settings/App.tsx
  renderer/settings/containers/UpdaterContainer.tsx
  src/Application.ts
Labels: Type: Enhancement

#52 fix: high GPU usage
  renderer/components/Marquee.tsx
  renderer/lyrics/SideBar.tsx
  renderer/main/components/LyricProgressBar.tsx
  renderer/main/components/LyricsItem.tsx
Labels: Type: Bug

#45 feat: DirectX Game Overlay
  assets/overlay/electron-overlay.node
  assets/overlay/injector_helper.exe
  assets/overlay/injector_helper.x64.exe
  assets/overlay/n_overlay.dll
  assets/overlay/n_overlay.x64.dll
  package-lock.json
  package.json
  patches/hmc-win32+1.3.6.patch
  renderer/alspotron.d.ts
  renderer/components/Marquee.tsx
  renderer/hooks/useGameList.ts
  renderer/hooks/usePlayingGame.ts
  renderer/settings/App.tsx
  renderer/settings/components/PresetCard.tsx
  renderer/settings/containers/GameContainer.tsx
  renderer/settings/containers/GameListContainer.tsx
  renderer/style.css
  src/Application.ts
  src/config.ts
  src/electron-overlay.d.ts
  src/exe-icon-extractor.d.ts
  src/preload.ts
  src/wql-process-monitor.d.ts
  tsconfig.json
Labels: Type: Enhancement, Tag: Help Wanted, Platform: Windows

#60 fix: fix segfault on specific environment
  src/Application.ts
Labels: Type: Bug, Platform: Windows

#66 fix: overlay bugs (position, overlay initalization, 32bit support)
  assets/overlay/electron-overlay.ia32.node
  assets/overlay/electron-overlay.node
  assets/overlay/injector_helper.exe
  assets/overlay/injector_helper.x64.exe
  assets/overlay/n_overlay.dll
  assets/overlay/n_overlay.x64.dll
  index.ts
  src/Application.ts
  src/config.ts
Labels: Type: Bug, Platform: Windows

#62 refactor: 코드 정리 및 스타일 개선
  .eslintrc.js
  index.ts
  package.json
  renderer/alsong.d.ts
  renderer/alspotron.d.ts
  renderer/components/Card.tsx
  renderer/components/Layout.tsx
  renderer/components/Marquee.tsx
  renderer/components/PlayingInfoProvider.tsx
  renderer/components/Select.tsx
  renderer/components/Spinner.tsx
  renderer/components/Titlebar.tsx
  renderer/hooks/useConfig.ts
  renderer/hooks/useGameList.ts
  renderer/hooks/useLyric.ts
  renderer/hooks/useLyricMapper.ts
  renderer/hooks/usePlayingGame.ts
  renderer/lyrics/App.tsx
  renderer/lyrics/SideBar.tsx
  renderer/lyrics/index.tsx
  renderer/main/App.tsx
  renderer/main/components/AnchoredView.tsx
  renderer/main/components/LyricProgressBar.tsx
  renderer/main/components/Lyrics.tsx
  renderer/main/components/LyricsItem.tsx
  renderer/main/index.tsx
  renderer/settings/App.tsx
  renderer/settings/components/ColorPicker.tsx
  renderer/settings/components/ListItem.tsx
  renderer/settings/components/ListView.tsx
  renderer/settings/components/PresetCard.tsx
  renderer/settings/containers/GameContainer.tsx
  renderer/settings/containers/GameListContainer.tsx
  renderer/settings/containers/InfoContainer.tsx
  renderer/settings/containers/PositionContainer.tsx
  renderer/settings/containers/ThemeContainer.tsx
  renderer/settings/index.tsx
  src/Application.ts
  src/config.ts
  src/electron-overlay.d.ts
  src/preload.ts
  tsconfig.json
  utils/resource.ts
Labels: Type: Code Style Change

#69 feat: use sorted vectors instead of tree-based associative map / use TSTL instead of js-sdsl
  package-lock.json
  package.json
  renderer/components/PlayingInfoProvider.tsx
  renderer/hooks/useLyric.ts
  renderer/lyrics/SideBar.tsx
Labels: Type: Dependency

#75 feat: optimize bundle size 🚀
  .eslintignore
  assets/electron-overlay.ia32.node
  assets/electron-overlay.node
  assets/injector_helper.exe
  assets/injector_helper.x64.exe
  assets/n_overlay.dll
  assets/n_overlay.x64.dll
  package-lock.json
  package.json
  renderer/settings/App.tsx
  rollup.main.config.ts
  rollup.preload.config.ts
  src/Application.ts
  vite.renderer.config.ts
Labels: Type: Enhancement

#79 fix: (종속성 호환 문제로 인해) 비 Windows 환경에서 실행이 불가능하던 오류 해결
  package-lock.json
  package.json
  renderer/settings/App.tsx
  src/Application.ts
Labels: Type: Bug, Platform: macOS, Platform: Linux (KDE), Platform: Linux (Gnome)

#90 feat(koa-body): type assertion
  package-lock.json
  package.json
  renderer/alsong.d.ts
  renderer/components/PlayingInfoProvider.tsx
  renderer/types.ts
  src/Application.ts
  src/types.ts
Labels: Type: Enhancement

#121 hotfix: fix #117, fix #118
  renderer/main/components/AnchoredView.tsx
  renderer/main/components/Lyrics.tsx
  renderer/main/components/LyricsTransition.tsx
Labels: Type: Bug

#120 hotfix: fix #116
  src/Application.ts
Labels: Type: Bug

#122 fix: fix #83
  renderer/hooks/useLyric.ts
Labels: Type: Bug

#123 feat: 멀티모니터 지원 추가
  package-lock.json
  package.json
  renderer/components/Select.tsx
  renderer/settings/containers/PositionContainer.tsx
  rollup.main.config.ts
  src/Application.ts
  src/exe-icon-extractor.d.ts
Labels: Type: Enhancement

#129 feat: resolve #81
  renderer/main/App.tsx
  renderer/main/components/Lyrics.tsx
  renderer/main/components/LyricsTransition.tsx
  renderer/settings/containers/ThemeContainer.tsx
  src/config.ts
Labels: Type: Enhancement

#135 fix: Fixed English translation typos
  README-i18n/en.md
  common/intl/translations/en.json
Labels: Type: Enhancement

#131 feat: support i18n
  README-i18n/de.md
  README-i18n/en.md
  README-i18n/ja.md
  README.md
  common/config.ts
  common/intl/index.ts
  common/intl/translations/de.json
  common/intl/translations/en.json
  common/intl/translations/ja.json
  common/intl/translations/ko.json
  package-lock.json
  package.json
  renderer/hooks/useConfig.ts
  renderer/hooks/useGameList.ts
  renderer/hooks/useLyricMapper.ts
  renderer/lyrics.html
  renderer/lyrics/App.tsx
  renderer/lyrics/SideBar.tsx
  renderer/main/App.tsx
  renderer/settings.html
  renderer/settings/App.tsx
  renderer/settings/components/UserCSSEditor.tsx
  renderer/settings/containers/GameContainer.tsx
  renderer/settings/containers/GameListContainer.tsx
  renderer/settings/containers/InfoContainer.tsx
  renderer/settings/containers/LanguageContainer.tsx
  renderer/settings/containers/PositionContainer.tsx
  renderer/settings/containers/ThemeContainer.tsx
  src/Application.ts
Labels: Type: Enhancement
